product: pd-table-service
version: "0.1.0"
environment:
  type: local
  name: local
actors:
  - name: customer
    label: alpha
    version: latest
  - name: waiter
    label: alpha
    version: latest
